
server:
  port: 9000
logging:
  path: /Users/chenxj/Documents/Temp/
  
ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: development
  main:
    allow-bean-definition-overriding: true

---
spring:
  profiles: test